### PR TITLE
Fixes SD-361.

### PR DESCRIPTION
**Pull request by akegalj**
I am not sure if this is a valid process. Correct me if I'm wrong. I have fatched and merged with gitorious master branch, and pushed into githubs. I am not sure can these lead to some conflicts.

### CODE REVIEW

**Comment by wolftune** [comment]
Thanks, although this fix works, I was wondering: we might add other types of automated / fake-users ever that might get called something different from being the anonymousUser… do you think it could make sense to filter out users with negative user numbers instead of filtering this specific user?

**Comment by akegalj** [comment]
Yes, that would work too but Kind of feels like a hack, closer to the solution from C language. It is the simplest one. Are you sure there will be only two roles of users? On this page users with positive Id will be shown, users with negative Id wont. Is there a plan of adding more of this roles in future? (maybe they even exist)

Anyway I agree, that would fix this problem for now.

**Comment by wolftune** [comment]
Honestly, I'm not sure. The idea of making the special anonymous user be user -1 was itself sort of a hack. And I'm not sure we'll use any more negative users. But I know that since normal users are positive numbers, it seems sensible to not show negative users in /u. But really, I'm not certain about any of this except that we don't want the anonymous user shown in the normal list…

**Comment by nkaretnikov** [comment]
Right, we must filter out all negative users, not just the anonymous one.
[this](https://gitorious.org/snowdrift/snowdrift/merge_requests/51)
branch adds another special user (`deletedUser`), which allows us to keep content after a user deletes their account.

I agree that filtering like that feels like C, but there's no better way at the moment.
hardcoding (=/ anonymous) is even worse.  

Ideally, we must distinguish
special from ordinary users at the type level (with phantom types, not booleans), but
someone has to implement it first.

**Comment by akegalj** [comment]
@nkaretnikov 
But this phantom type solution won't make it safe in any of these scenarios:
```haskell
-- Shows all 'User's.
showUsers :: User Ordinary -> IO ()
showUsers _ = runDB (selectAllUsers) >>= doSomething

-- Somewhere in codebase one can do mutiple joins over user table
-- doing some wrong counting, bypassing phantom types
complexMultiTableJoin :: IO ()
complexMultiTableJoin = runDB $ UserTable `Join` TableA ...
```
Can we protect this scenarios anyhow? As I'm aware, we could do phantom types but it would solve only this isolated problem (not showing `Special` users under `/u`). Anyone new on codebase won't know about the `UserStatus` convention and could introduce a bug.

Am I missing the point?

**Comment by akegalj** [comment]
# SD-393
Needs aditional refactoring. I couldn't find in which module to put the function `countDiscussionAllCommentsDB`, so I cloned it twice. That needs to be fixed. Ideally put function in `Model.Discussion` module, but I'm running into cycle imports. For now the function `countDiscussionAllCommentsDB` is placed in `View.Project` and `Handler.Wiki`.

**Comment by wolftune** [comment]
Now that we have gotten into updating and merging the real master, this work should be probably made into pull-requests to the main master code instead of mine. Also, best to split things to new branches.

**Pull request closed without merging**
